name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permessi necessari per GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evita deploy multipli simultanei
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepara file per GitHub Pages
        run: |
          # Crea cartella per GitHub Pages
          mkdir -p gh-pages
          
          # Copia i file del plugin
          cp -r script gh-pages/ 2>/dev/null || true
          cp -r stili gh-pages/ 2>/dev/null || true
          cp *.jpg gh-pages/ 2>/dev/null || true
          cp *.png gh-pages/ 2>/dev/null || true
          cp *.html gh-pages/ 2>/dev/null || true
          cp *.js gh-pages/ 2>/dev/null || true
          cp manifest.json gh-pages/ 2>/dev/null || true
          
          # Crea il file ZIP
          cd gh-pages && zip -r ../extremelot-plugin.zip .
          cd ..
          
          # Metti il ZIP nella cartella di GitHub Pages
          cp extremelot-plugin.zip gh-pages/
          
          # Crea una pagina HTML semplice per il download
          cat > gh-pages/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="it">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Download ExtremeLot Plugin</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      max-width: 600px;
                      margin: 50px auto;
                      padding: 20px;
                      background: #f5f5f5;
                  }
                  .container {
                      background: white;
                      padding: 30px;
                      border-radius: 10px;
                      box-shadow: 0 4px 6px rgba(0,0,0,0.1);
                      text-align: center;
                  }
                  .download-btn {
                      display: inline-block;
                      background: #4CAF50;
                      color: white;
                      padding: 15px 30px;
                      text-decoration: none;
                      border-radius: 8px;
                      font-size: 18px;
                      margin: 20px 0;
                      transition: background 0.3s;
                  }
                  .download-btn:hover {
                      background: #45a049;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🔌 ExtremeLot Plugin</h1>
                  <p>Scarica l'ultima versione del plugin ExtremeLot.</p>
                  <a href="extremelot-plugin.zip" class="download-btn" download>
                      📦 Scarica Plugin
                  </a>
                  <p><small>File aggiornato automaticamente ad ogni commit.</small></p>
              </div>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './gh-pages'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3